/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModQueueRouteImport } from './routes/mod-queue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityFeedRouteImport } from './routes/_authenticated/activity-feed'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedClipCommandRouteImport } from './routes/_authenticated/clip-command'
import { Route as AuthenticatedClipsRouteImport } from './routes/_authenticated/clips'
import { Route as AuthenticatedCustomCommandsRouteImport } from './routes/_authenticated/custom-commands'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGiveawayRouteImport } from './routes/_authenticated/giveaway'
import { Route as AuthenticatedLinkInBioRouteImport } from './routes/_authenticated/link-in-bio'
import { Route as AuthenticatedLiveCounterRouteImport } from './routes/_authenticated/live-counter'
import { Route as AuthenticatedMarkPointsRouteImport } from './routes/_authenticated/mark-points'
import { Route as AuthenticatedMediaRequestsRouteImport } from './routes/_authenticated/media-requests'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BioSlugRouteImport } from './routes/bio.$slug'
import { Route as ClipIdRouteImport } from './routes/clip.$id'
import { Route as MarksTokenRouteImport } from './routes/marks.$token'
import { Route as OverlayPublicIdRouteImport } from './routes/overlay.$publicId'
import { Route as OverlayGiveawayRouteImport } from './routes/overlay.giveaway'
import { Route as OverlayMediaRequestRouteImport } from './routes/overlay.media-request'
import { Route as OverlayScheduleRouteImport } from './routes/overlay.schedule'
import { Route as OverlaySubathonTimerRouteImport } from './routes/overlay.subathon-timer'
import { Route as OverlayTiktokTapGoalRouteImport } from './routes/overlay.tiktok-tap-goal'
import { Route as OverlayTiktokTappersRouteImport } from './routes/overlay.tiktok-tappers'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as AuthenticatedWidgetsIndexRouteImport } from './routes/_authenticated/widgets.index'
import { Route as AuthenticatedWidgetsWidgetIdRouteImport } from './routes/_authenticated/widgets.$widgetId'
import { Route as MarksTokenMarkIdRouteImport } from './routes/marks.$token.$markId'
import { Route as AuthenticatedSubathonsIdControlRouteImport } from './routes/_authenticated/subathons.$id.control'
import { Route as AuthenticatedSubathonsIdOverlayRouteImport } from './routes/_authenticated/subathons.$id.overlay'
import { Route as AuthenticatedSubathonsIdRulesRouteImport } from './routes/_authenticated/subathons.$id.rules'
import { Route as AuthenticatedWidgetsWidgetIdIndexRouteImport } from './routes/_authenticated/widgets.$widgetId.index'
import { Route as AuthenticatedWidgetsWidgetIdControlRouteImport } from './routes/_authenticated/widgets.$widgetId.control'
import { Route as AuthenticatedWidgetsWidgetIdGoalRouteImport } from './routes/_authenticated/widgets.$widgetId.goal'
import { Route as AuthenticatedWidgetsWidgetIdRulesRouteImport } from './routes/_authenticated/widgets.$widgetId.rules'
import { Route as ApiAuthProviderCallbackRouteImport } from './routes/api/auth/$provider/callback'
import { Route as ApiAuthProviderStartRouteImport } from './routes/api/auth/$provider/start'
import { Route as ApiAuthCallbackTiktokRouteImport } from './routes/api/auth/callback/tiktok'
import { Route as ApiAuthSessionFinishRouteImport } from './routes/api/auth/session/finish'
import { Route as ApiLiveCounterLookupRouteImport } from './routes/api/live-counter/lookup'
import { Route as ApiTuwaiqpayBillsRouteImport } from './routes/api/tuwaiqpay/bills'
import { Route as ApiTuwaiqpayStatusRouteImport } from './routes/api/tuwaiqpay/status'
import { Route as ApiWebhooksTuwaiqpayPaymentRouteImport } from './routes/api/webhooks/tuwaiqpay-payment'
import { Route as ApiPublicClipIdRouteImport } from './routes/api/public/clip/$id'
import { Route as ApiPublicWebhooksKickRouteImport } from './routes/api/public/webhooks/kick'
import { Route as ApiPublicWebhooksProCheckoutRouteImport } from './routes/api/public/webhooks/pro-checkout'
import { Route as ApiPublicWebhooksStreamelementsRouteImport } from './routes/api/public/webhooks/streamelements'
import { Route as ApiPublicWebhooksStreamlabsRouteImport } from './routes/api/public/webhooks/streamlabs'
import { Route as ApiPublicWebhooksTwitchRouteImport } from './routes/api/public/webhooks/twitch'
import { Route as ApiPublicAuthProviderCallbackRouteImport } from './routes/api/public/auth/$provider/callback'
import { Route as ApiPublicAuthProviderStartRouteImport } from './routes/api/public/auth/$provider/start'
import { Route as ApiPublicGiveawayTokenLiveRouteImport } from './routes/api/public/giveaway/$token/live'
import { Route as ApiPublicLinkInBioSlugLiveRouteImport } from './routes/api/public/link-in-bio/$slug/live'
import { Route as ApiPublicMarksTokenGateRouteImport } from './routes/api/public/marks/$token/gate'
import { Route as ApiPublicMarksTokenLiveRouteImport } from './routes/api/public/marks/$token/live'
import { Route as ApiPublicMarksTokenStatusRouteImport } from './routes/api/public/marks/$token/status'
import { Route as ApiPublicMediaRequestTokenAdvanceRouteImport } from './routes/api/public/media-request/$token/advance'
import { Route as ApiPublicMediaRequestTokenLiveRouteImport } from './routes/api/public/media-request/$token/live'
import { Route as ApiPublicMediaRequestTokenStreamRouteImport } from './routes/api/public/media-request/$token/stream'
import { Route as ApiPublicModQueueTokenActionRouteImport } from './routes/api/public/mod-queue/$token/action'
import { Route as ApiPublicModQueueTokenQueueRouteImport } from './routes/api/public/mod-queue/$token/queue'
import { Route as ApiPublicOverlayPublicIdLiveRouteImport } from './routes/api/public/overlay/$publicId/live'
import { Route as ApiPublicOverlayPublicIdMetaRouteImport } from './routes/api/public/overlay/$publicId/meta'
import { Route as ApiPublicOverlayPublicIdStreamRouteImport } from './routes/api/public/overlay/$publicId/stream'
import { Route as ApiPublicScheduleTokenIcsRouteImport } from './routes/api/public/schedule/$token/ics'
import { Route as ApiPublicScheduleTokenLiveRouteImport } from './routes/api/public/schedule/$token/live'
import { Route as ApiPublicMarksTokenVodMarkIdRouteImport } from './routes/api/public/marks/$token/vod.$markId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModQueueRoute = ModQueueRouteImport.update({
  id: '/mod-queue',
  path: '/mod-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityFeedRoute =
  AuthenticatedActivityFeedRouteImport.update({
    id: '/activity-feed',
    path: '/activity-feed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClipCommandRoute =
  AuthenticatedClipCommandRouteImport.update({
    id: '/clip-command',
    path: '/clip-command',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClipsRoute = AuthenticatedClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomCommandsRoute =
  AuthenticatedCustomCommandsRouteImport.update({
    id: '/custom-commands',
    path: '/custom-commands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiveawayRoute = AuthenticatedGiveawayRouteImport.update({
  id: '/giveaway',
  path: '/giveaway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkInBioRoute = AuthenticatedLinkInBioRouteImport.update({
  id: '/link-in-bio',
  path: '/link-in-bio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveCounterRoute =
  AuthenticatedLiveCounterRouteImport.update({
    id: '/live-counter',
    path: '/live-counter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarkPointsRoute = AuthenticatedMarkPointsRouteImport.update({
  id: '/mark-points',
  path: '/mark-points',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRequestsRoute =
  AuthenticatedMediaRequestsRouteImport.update({
    id: '/media-requests',
    path: '/media-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BioSlugRoute = BioSlugRouteImport.update({
  id: '/bio/$slug',
  path: '/bio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipIdRoute = ClipIdRouteImport.update({
  id: '/clip/$id',
  path: '/clip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksTokenRoute = MarksTokenRouteImport.update({
  id: '/marks/$token',
  path: '/marks/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayPublicIdRoute = OverlayPublicIdRouteImport.update({
  id: '/overlay/$publicId',
  path: '/overlay/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayGiveawayRoute = OverlayGiveawayRouteImport.update({
  id: '/overlay/giveaway',
  path: '/overlay/giveaway',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayMediaRequestRoute = OverlayMediaRequestRouteImport.update({
  id: '/overlay/media-request',
  path: '/overlay/media-request',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayScheduleRoute = OverlayScheduleRouteImport.update({
  id: '/overlay/schedule',
  path: '/overlay/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaySubathonTimerRoute = OverlaySubathonTimerRouteImport.update({
  id: '/overlay/subathon-timer',
  path: '/overlay/subathon-timer',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTiktokTapGoalRoute = OverlayTiktokTapGoalRouteImport.update({
  id: '/overlay/tiktok-tap-goal',
  path: '/overlay/tiktok-tap-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTiktokTappersRoute = OverlayTiktokTappersRouteImport.update({
  id: '/overlay/tiktok-tappers',
  path: '/overlay/tiktok-tappers',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWidgetsIndexRoute =
  AuthenticatedWidgetsIndexRouteImport.update({
    id: '/widgets/',
    path: '/widgets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdRoute =
  AuthenticatedWidgetsWidgetIdRouteImport.update({
    id: '/widgets/$widgetId',
    path: '/widgets/$widgetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MarksTokenMarkIdRoute = MarksTokenMarkIdRouteImport.update({
  id: '/$markId',
  path: '/$markId',
  getParentRoute: () => MarksTokenRoute,
} as any)
const AuthenticatedSubathonsIdControlRoute =
  AuthenticatedSubathonsIdControlRouteImport.update({
    id: '/subathons/$id/control',
    path: '/subathons/$id/control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubathonsIdOverlayRoute =
  AuthenticatedSubathonsIdOverlayRouteImport.update({
    id: '/subathons/$id/overlay',
    path: '/subathons/$id/overlay',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubathonsIdRulesRoute =
  AuthenticatedSubathonsIdRulesRouteImport.update({
    id: '/subathons/$id/rules',
    path: '/subathons/$id/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdIndexRoute =
  AuthenticatedWidgetsWidgetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdControlRoute =
  AuthenticatedWidgetsWidgetIdControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdGoalRoute =
  AuthenticatedWidgetsWidgetIdGoalRouteImport.update({
    id: '/goal',
    path: '/goal',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdRulesRoute =
  AuthenticatedWidgetsWidgetIdRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const ApiAuthProviderCallbackRoute = ApiAuthProviderCallbackRouteImport.update({
  id: '/api/auth/$provider/callback',
  path: '/api/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProviderStartRoute = ApiAuthProviderStartRouteImport.update({
  id: '/api/auth/$provider/start',
  path: '/api/auth/$provider/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackTiktokRoute = ApiAuthCallbackTiktokRouteImport.update({
  id: '/api/auth/callback/tiktok',
  path: '/api/auth/callback/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionFinishRoute = ApiAuthSessionFinishRouteImport.update({
  id: '/api/auth/session/finish',
  path: '/api/auth/session/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCounterLookupRoute = ApiLiveCounterLookupRouteImport.update({
  id: '/api/live-counter/lookup',
  path: '/api/live-counter/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTuwaiqpayBillsRoute = ApiTuwaiqpayBillsRouteImport.update({
  id: '/api/tuwaiqpay/bills',
  path: '/api/tuwaiqpay/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTuwaiqpayStatusRoute = ApiTuwaiqpayStatusRouteImport.update({
  id: '/api/tuwaiqpay/status',
  path: '/api/tuwaiqpay/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTuwaiqpayPaymentRoute = ApiWebhooksTuwaiqpayPaymentRouteImport.update({
  id: '/api/webhooks/tuwaiqpay-payment',
  path: '/api/webhooks/tuwaiqpay-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipIdRoute = ApiPublicClipIdRouteImport.update({
  id: '/api/public/clip/$id',
  path: '/api/public/clip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKickRoute = ApiPublicWebhooksKickRouteImport.update({
  id: '/api/public/webhooks/kick',
  path: '/api/public/webhooks/kick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksProCheckoutRoute =
  ApiPublicWebhooksProCheckoutRouteImport.update({
    id: '/api/public/webhooks/pro-checkout',
    path: '/api/public/webhooks/pro-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStreamelementsRoute =
  ApiPublicWebhooksStreamelementsRouteImport.update({
    id: '/api/public/webhooks/streamelements',
    path: '/api/public/webhooks/streamelements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStreamlabsRoute =
  ApiPublicWebhooksStreamlabsRouteImport.update({
    id: '/api/public/webhooks/streamlabs',
    path: '/api/public/webhooks/streamlabs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTwitchRoute = ApiPublicWebhooksTwitchRouteImport.update({
  id: '/api/public/webhooks/twitch',
  path: '/api/public/webhooks/twitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthProviderCallbackRoute =
  ApiPublicAuthProviderCallbackRouteImport.update({
    id: '/api/public/auth/$provider/callback',
    path: '/api/public/auth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthProviderStartRoute =
  ApiPublicAuthProviderStartRouteImport.update({
    id: '/api/public/auth/$provider/start',
    path: '/api/public/auth/$provider/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGiveawayTokenLiveRoute =
  ApiPublicGiveawayTokenLiveRouteImport.update({
    id: '/api/public/giveaway/$token/live',
    path: '/api/public/giveaway/$token/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLinkInBioSlugLiveRoute =
  ApiPublicLinkInBioSlugLiveRouteImport.update({
    id: '/api/public/link-in-bio/$slug/live',
    path: '/api/public/link-in-bio/$slug/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarksTokenGateRoute = ApiPublicMarksTokenGateRouteImport.update({
  id: '/api/public/marks/$token/gate',
  path: '/api/public/marks/$token/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarksTokenLiveRoute = ApiPublicMarksTokenLiveRouteImport.update({
  id: '/api/public/marks/$token/live',
  path: '/api/public/marks/$token/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarksTokenStatusRoute =
  ApiPublicMarksTokenStatusRouteImport.update({
    id: '/api/public/marks/$token/status',
    path: '/api/public/marks/$token/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenAdvanceRoute =
  ApiPublicMediaRequestTokenAdvanceRouteImport.update({
    id: '/api/public/media-request/$token/advance',
    path: '/api/public/media-request/$token/advance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenLiveRoute =
  ApiPublicMediaRequestTokenLiveRouteImport.update({
    id: '/api/public/media-request/$token/live',
    path: '/api/public/media-request/$token/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenStreamRoute =
  ApiPublicMediaRequestTokenStreamRouteImport.update({
    id: '/api/public/media-request/$token/stream',
    path: '/api/public/media-request/$token/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicModQueueTokenActionRoute =
  ApiPublicModQueueTokenActionRouteImport.update({
    id: '/api/public/mod-queue/$token/action',
    path: '/api/public/mod-queue/$token/action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicModQueueTokenQueueRoute =
  ApiPublicModQueueTokenQueueRouteImport.update({
    id: '/api/public/mod-queue/$token/queue',
    path: '/api/public/mod-queue/$token/queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdLiveRoute =
  ApiPublicOverlayPublicIdLiveRouteImport.update({
    id: '/api/public/overlay/$publicId/live',
    path: '/api/public/overlay/$publicId/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdMetaRoute =
  ApiPublicOverlayPublicIdMetaRouteImport.update({
    id: '/api/public/overlay/$publicId/meta',
    path: '/api/public/overlay/$publicId/meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdStreamRoute =
  ApiPublicOverlayPublicIdStreamRouteImport.update({
    id: '/api/public/overlay/$publicId/stream',
    path: '/api/public/overlay/$publicId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScheduleTokenIcsRoute =
  ApiPublicScheduleTokenIcsRouteImport.update({
    id: '/api/public/schedule/$token/ics',
    path: '/api/public/schedule/$token/ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScheduleTokenLiveRoute =
  ApiPublicScheduleTokenLiveRouteImport.update({
    id: '/api/public/schedule/$token/live',
    path: '/api/public/schedule/$token/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarksTokenVodMarkIdRoute =
  ApiPublicMarksTokenVodMarkIdRouteImport.update({
    id: '/api/public/marks/$token/vod/$markId',
    path: '/api/public/marks/$token/vod/$markId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/clip-command': typeof AuthenticatedClipCommandRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/giveaway': typeof AuthenticatedGiveawayRoute
  '/link-in-bio': typeof AuthenticatedLinkInBioRoute
  '/live-counter': typeof AuthenticatedLiveCounterRoute
  '/mark-points': typeof AuthenticatedMarkPointsRoute
  '/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bio/$slug': typeof BioSlugRoute
  '/clip/$id': typeof ClipIdRoute
  '/marks/$token': typeof MarksTokenRouteWithChildren
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/schedule': typeof OverlayScheduleRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/u/$slug': typeof USlugRoute
  '/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  '/marks/$token/$markId': typeof MarksTokenMarkIdRoute
  '/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/$provider/callback': typeof ApiAuthProviderCallbackRoute
  '/api/auth/$provider/start': typeof ApiAuthProviderStartRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/auth/session/finish': typeof ApiAuthSessionFinishRoute
  '/api/live-counter/lookup': typeof ApiLiveCounterLookupRoute
  '/api/tuwaiqpay/bills': typeof ApiTuwaiqpayBillsRoute
  '/api/tuwaiqpay/status': typeof ApiTuwaiqpayStatusRoute
  '/api/webhooks/tuwaiqpay-payment': typeof ApiWebhooksTuwaiqpayPaymentRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/pro-checkout': typeof ApiPublicWebhooksProCheckoutRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/widgets/$widgetId/': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/link-in-bio/$slug/live': typeof ApiPublicLinkInBioSlugLiveRoute
  '/api/public/marks/$token/gate': typeof ApiPublicMarksTokenGateRoute
  '/api/public/marks/$token/live': typeof ApiPublicMarksTokenLiveRoute
  '/api/public/marks/$token/status': typeof ApiPublicMarksTokenStatusRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
  '/api/public/schedule/$token/ics': typeof ApiPublicScheduleTokenIcsRoute
  '/api/public/schedule/$token/live': typeof ApiPublicScheduleTokenLiveRoute
  '/api/public/marks/$token/vod/$markId': typeof ApiPublicMarksTokenVodMarkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/clip-command': typeof AuthenticatedClipCommandRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/giveaway': typeof AuthenticatedGiveawayRoute
  '/link-in-bio': typeof AuthenticatedLinkInBioRoute
  '/live-counter': typeof AuthenticatedLiveCounterRoute
  '/mark-points': typeof AuthenticatedMarkPointsRoute
  '/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bio/$slug': typeof BioSlugRoute
  '/clip/$id': typeof ClipIdRoute
  '/marks/$token': typeof MarksTokenRouteWithChildren
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/schedule': typeof OverlayScheduleRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/u/$slug': typeof USlugRoute
  '/marks/$token/$markId': typeof MarksTokenMarkIdRoute
  '/widgets': typeof AuthenticatedWidgetsIndexRoute
  '/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/$provider/callback': typeof ApiAuthProviderCallbackRoute
  '/api/auth/$provider/start': typeof ApiAuthProviderStartRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/auth/session/finish': typeof ApiAuthSessionFinishRoute
  '/api/live-counter/lookup': typeof ApiLiveCounterLookupRoute
  '/api/tuwaiqpay/bills': typeof ApiTuwaiqpayBillsRoute
  '/api/tuwaiqpay/status': typeof ApiTuwaiqpayStatusRoute
  '/api/webhooks/tuwaiqpay-payment': typeof ApiWebhooksTuwaiqpayPaymentRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/pro-checkout': typeof ApiPublicWebhooksProCheckoutRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/link-in-bio/$slug/live': typeof ApiPublicLinkInBioSlugLiveRoute
  '/api/public/marks/$token/gate': typeof ApiPublicMarksTokenGateRoute
  '/api/public/marks/$token/live': typeof ApiPublicMarksTokenLiveRoute
  '/api/public/marks/$token/status': typeof ApiPublicMarksTokenStatusRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
  '/api/public/schedule/$token/ics': typeof ApiPublicScheduleTokenIcsRoute
  '/api/public/schedule/$token/live': typeof ApiPublicScheduleTokenLiveRoute
  '/api/public/marks/$token/vod/$markId': typeof ApiPublicMarksTokenVodMarkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/clip-command': typeof AuthenticatedClipCommandRoute
  '/_authenticated/clips': typeof AuthenticatedClipsRoute
  '/_authenticated/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/giveaway': typeof AuthenticatedGiveawayRoute
  '/_authenticated/link-in-bio': typeof AuthenticatedLinkInBioRoute
  '/_authenticated/live-counter': typeof AuthenticatedLiveCounterRoute
  '/_authenticated/mark-points': typeof AuthenticatedMarkPointsRoute
  '/_authenticated/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bio/$slug': typeof BioSlugRoute
  '/clip/$id': typeof ClipIdRoute
  '/marks/$token': typeof MarksTokenRouteWithChildren
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/schedule': typeof OverlayScheduleRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/u/$slug': typeof USlugRoute
  '/_authenticated/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  '/marks/$token/$markId': typeof MarksTokenMarkIdRoute
  '/_authenticated/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/_authenticated/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/_authenticated/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/_authenticated/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/_authenticated/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/_authenticated/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/_authenticated/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/$provider/callback': typeof ApiAuthProviderCallbackRoute
  '/api/auth/$provider/start': typeof ApiAuthProviderStartRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/auth/session/finish': typeof ApiAuthSessionFinishRoute
  '/api/live-counter/lookup': typeof ApiLiveCounterLookupRoute
  '/api/tuwaiqpay/bills': typeof ApiTuwaiqpayBillsRoute
  '/api/tuwaiqpay/status': typeof ApiTuwaiqpayStatusRoute
  '/api/webhooks/tuwaiqpay-payment': typeof ApiWebhooksTuwaiqpayPaymentRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/pro-checkout': typeof ApiPublicWebhooksProCheckoutRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/_authenticated/widgets/$widgetId/': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/link-in-bio/$slug/live': typeof ApiPublicLinkInBioSlugLiveRoute
  '/api/public/marks/$token/gate': typeof ApiPublicMarksTokenGateRoute
  '/api/public/marks/$token/live': typeof ApiPublicMarksTokenLiveRoute
  '/api/public/marks/$token/status': typeof ApiPublicMarksTokenStatusRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
  '/api/public/schedule/$token/ics': typeof ApiPublicScheduleTokenIcsRoute
  '/api/public/schedule/$token/live': typeof ApiPublicScheduleTokenLiveRoute
  '/api/public/marks/$token/vod/$markId': typeof ApiPublicMarksTokenVodMarkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/activity-feed'
    | '/analytics'
    | '/clip-command'
    | '/clips'
    | '/custom-commands'
    | '/dashboard'
    | '/giveaway'
    | '/link-in-bio'
    | '/live-counter'
    | '/mark-points'
    | '/media-requests'
    | '/schedule'
    | '/settings'
    | '/subscription'
    | '/welcome'
    | '/auth/callback'
    | '/bio/$slug'
    | '/clip/$id'
    | '/marks/$token'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/schedule'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/u/$slug'
    | '/widgets/$widgetId'
    | '/marks/$token/$markId'
    | '/widgets/'
    | '/subathons/$id/control'
    | '/subathons/$id/overlay'
    | '/subathons/$id/rules'
    | '/widgets/$widgetId/control'
    | '/widgets/$widgetId/goal'
    | '/widgets/$widgetId/rules'
    | '/api/auth/$provider/callback'
    | '/api/auth/$provider/start'
    | '/api/auth/callback/tiktok'
    | '/api/auth/session/finish'
    | '/api/live-counter/lookup'
    | '/api/tuwaiqpay/bills'
    | '/api/tuwaiqpay/status'
    | '/api/webhooks/tuwaiqpay-payment'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/pro-checkout'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/widgets/$widgetId/'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/link-in-bio/$slug/live'
    | '/api/public/marks/$token/gate'
    | '/api/public/marks/$token/live'
    | '/api/public/marks/$token/status'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
    | '/api/public/schedule/$token/ics'
    | '/api/public/schedule/$token/live'
    | '/api/public/marks/$token/vod/$markId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/activity-feed'
    | '/analytics'
    | '/clip-command'
    | '/clips'
    | '/custom-commands'
    | '/dashboard'
    | '/giveaway'
    | '/link-in-bio'
    | '/live-counter'
    | '/mark-points'
    | '/media-requests'
    | '/schedule'
    | '/settings'
    | '/subscription'
    | '/welcome'
    | '/auth/callback'
    | '/bio/$slug'
    | '/clip/$id'
    | '/marks/$token'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/schedule'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/u/$slug'
    | '/marks/$token/$markId'
    | '/widgets'
    | '/subathons/$id/control'
    | '/subathons/$id/overlay'
    | '/subathons/$id/rules'
    | '/widgets/$widgetId/control'
    | '/widgets/$widgetId/goal'
    | '/widgets/$widgetId/rules'
    | '/api/auth/$provider/callback'
    | '/api/auth/$provider/start'
    | '/api/auth/callback/tiktok'
    | '/api/auth/session/finish'
    | '/api/live-counter/lookup'
    | '/api/tuwaiqpay/bills'
    | '/api/tuwaiqpay/status'
    | '/api/webhooks/tuwaiqpay-payment'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/pro-checkout'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/widgets/$widgetId'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/link-in-bio/$slug/live'
    | '/api/public/marks/$token/gate'
    | '/api/public/marks/$token/live'
    | '/api/public/marks/$token/status'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
    | '/api/public/schedule/$token/ics'
    | '/api/public/schedule/$token/live'
    | '/api/public/marks/$token/vod/$markId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activity-feed'
    | '/_authenticated/analytics'
    | '/_authenticated/clip-command'
    | '/_authenticated/clips'
    | '/_authenticated/custom-commands'
    | '/_authenticated/dashboard'
    | '/_authenticated/giveaway'
    | '/_authenticated/link-in-bio'
    | '/_authenticated/live-counter'
    | '/_authenticated/mark-points'
    | '/_authenticated/media-requests'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/welcome'
    | '/auth/callback'
    | '/bio/$slug'
    | '/clip/$id'
    | '/marks/$token'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/schedule'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/u/$slug'
    | '/_authenticated/widgets/$widgetId'
    | '/marks/$token/$markId'
    | '/_authenticated/widgets/'
    | '/_authenticated/subathons/$id/control'
    | '/_authenticated/subathons/$id/overlay'
    | '/_authenticated/subathons/$id/rules'
    | '/_authenticated/widgets/$widgetId/control'
    | '/_authenticated/widgets/$widgetId/goal'
    | '/_authenticated/widgets/$widgetId/rules'
    | '/api/auth/$provider/callback'
    | '/api/auth/$provider/start'
    | '/api/auth/callback/tiktok'
    | '/api/auth/session/finish'
    | '/api/live-counter/lookup'
    | '/api/tuwaiqpay/bills'
    | '/api/tuwaiqpay/status'
    | '/api/webhooks/tuwaiqpay-payment'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/pro-checkout'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/_authenticated/widgets/$widgetId/'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/link-in-bio/$slug/live'
    | '/api/public/marks/$token/gate'
    | '/api/public/marks/$token/live'
    | '/api/public/marks/$token/status'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
    | '/api/public/schedule/$token/ics'
    | '/api/public/schedule/$token/live'
    | '/api/public/marks/$token/vod/$markId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModQueueRoute: typeof ModQueueRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BioSlugRoute: typeof BioSlugRoute
  ClipIdRoute: typeof ClipIdRoute
  MarksTokenRoute: typeof MarksTokenRouteWithChildren
  OverlayPublicIdRoute: typeof OverlayPublicIdRoute
  OverlayGiveawayRoute: typeof OverlayGiveawayRoute
  OverlayMediaRequestRoute: typeof OverlayMediaRequestRoute
  OverlayScheduleRoute: typeof OverlayScheduleRoute
  OverlaySubathonTimerRoute: typeof OverlaySubathonTimerRoute
  OverlayTiktokTapGoalRoute: typeof OverlayTiktokTapGoalRoute
  OverlayTiktokTappersRoute: typeof OverlayTiktokTappersRoute
  USlugRoute: typeof USlugRoute
  ApiAuthProviderCallbackRoute: typeof ApiAuthProviderCallbackRoute
  ApiAuthProviderStartRoute: typeof ApiAuthProviderStartRoute
  ApiAuthCallbackTiktokRoute: typeof ApiAuthCallbackTiktokRoute
  ApiAuthSessionFinishRoute: typeof ApiAuthSessionFinishRoute
  ApiLiveCounterLookupRoute: typeof ApiLiveCounterLookupRoute
  ApiTuwaiqpayBillsRoute: typeof ApiTuwaiqpayBillsRoute
  ApiTuwaiqpayStatusRoute: typeof ApiTuwaiqpayStatusRoute
  ApiWebhooksTuwaiqpayPaymentRoute: typeof ApiWebhooksTuwaiqpayPaymentRoute
  ApiPublicClipIdRoute: typeof ApiPublicClipIdRoute
  ApiPublicWebhooksKickRoute: typeof ApiPublicWebhooksKickRoute
  ApiPublicWebhooksProCheckoutRoute: typeof ApiPublicWebhooksProCheckoutRoute
  ApiPublicWebhooksStreamelementsRoute: typeof ApiPublicWebhooksStreamelementsRoute
  ApiPublicWebhooksStreamlabsRoute: typeof ApiPublicWebhooksStreamlabsRoute
  ApiPublicWebhooksTwitchRoute: typeof ApiPublicWebhooksTwitchRoute
  ApiPublicAuthProviderCallbackRoute: typeof ApiPublicAuthProviderCallbackRoute
  ApiPublicAuthProviderStartRoute: typeof ApiPublicAuthProviderStartRoute
  ApiPublicGiveawayTokenLiveRoute: typeof ApiPublicGiveawayTokenLiveRoute
  ApiPublicLinkInBioSlugLiveRoute: typeof ApiPublicLinkInBioSlugLiveRoute
  ApiPublicMarksTokenGateRoute: typeof ApiPublicMarksTokenGateRoute
  ApiPublicMarksTokenLiveRoute: typeof ApiPublicMarksTokenLiveRoute
  ApiPublicMarksTokenStatusRoute: typeof ApiPublicMarksTokenStatusRoute
  ApiPublicMediaRequestTokenAdvanceRoute: typeof ApiPublicMediaRequestTokenAdvanceRoute
  ApiPublicMediaRequestTokenLiveRoute: typeof ApiPublicMediaRequestTokenLiveRoute
  ApiPublicMediaRequestTokenStreamRoute: typeof ApiPublicMediaRequestTokenStreamRoute
  ApiPublicModQueueTokenActionRoute: typeof ApiPublicModQueueTokenActionRoute
  ApiPublicModQueueTokenQueueRoute: typeof ApiPublicModQueueTokenQueueRoute
  ApiPublicOverlayPublicIdLiveRoute: typeof ApiPublicOverlayPublicIdLiveRoute
  ApiPublicOverlayPublicIdMetaRoute: typeof ApiPublicOverlayPublicIdMetaRoute
  ApiPublicOverlayPublicIdStreamRoute: typeof ApiPublicOverlayPublicIdStreamRoute
  ApiPublicScheduleTokenIcsRoute: typeof ApiPublicScheduleTokenIcsRoute
  ApiPublicScheduleTokenLiveRoute: typeof ApiPublicScheduleTokenLiveRoute
  ApiPublicMarksTokenVodMarkIdRoute: typeof ApiPublicMarksTokenVodMarkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-queue': {
      id: '/mod-queue'
      path: '/mod-queue'
      fullPath: '/mod-queue'
      preLoaderRoute: typeof ModQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity-feed': {
      id: '/_authenticated/activity-feed'
      path: '/activity-feed'
      fullPath: '/activity-feed'
      preLoaderRoute: typeof AuthenticatedActivityFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clip-command': {
      id: '/_authenticated/clip-command'
      path: '/clip-command'
      fullPath: '/clip-command'
      preLoaderRoute: typeof AuthenticatedClipCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clips': {
      id: '/_authenticated/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AuthenticatedClipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custom-commands': {
      id: '/_authenticated/custom-commands'
      path: '/custom-commands'
      fullPath: '/custom-commands'
      preLoaderRoute: typeof AuthenticatedCustomCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giveaway': {
      id: '/_authenticated/giveaway'
      path: '/giveaway'
      fullPath: '/giveaway'
      preLoaderRoute: typeof AuthenticatedGiveawayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link-in-bio': {
      id: '/_authenticated/link-in-bio'
      path: '/link-in-bio'
      fullPath: '/link-in-bio'
      preLoaderRoute: typeof AuthenticatedLinkInBioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-counter': {
      id: '/_authenticated/live-counter'
      path: '/live-counter'
      fullPath: '/live-counter'
      preLoaderRoute: typeof AuthenticatedLiveCounterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mark-points': {
      id: '/_authenticated/mark-points'
      path: '/mark-points'
      fullPath: '/mark-points'
      preLoaderRoute: typeof AuthenticatedMarkPointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media-requests': {
      id: '/_authenticated/media-requests'
      path: '/media-requests'
      fullPath: '/media-requests'
      preLoaderRoute: typeof AuthenticatedMediaRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio/$slug': {
      id: '/bio/$slug'
      path: '/bio/$slug'
      fullPath: '/bio/$slug'
      preLoaderRoute: typeof BioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$id': {
      id: '/clip/$id'
      path: '/clip/$id'
      fullPath: '/clip/$id'
      preLoaderRoute: typeof ClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks/$token': {
      id: '/marks/$token'
      path: '/marks/$token'
      fullPath: '/marks/$token'
      preLoaderRoute: typeof MarksTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$publicId': {
      id: '/overlay/$publicId'
      path: '/overlay/$publicId'
      fullPath: '/overlay/$publicId'
      preLoaderRoute: typeof OverlayPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/giveaway': {
      id: '/overlay/giveaway'
      path: '/overlay/giveaway'
      fullPath: '/overlay/giveaway'
      preLoaderRoute: typeof OverlayGiveawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/media-request': {
      id: '/overlay/media-request'
      path: '/overlay/media-request'
      fullPath: '/overlay/media-request'
      preLoaderRoute: typeof OverlayMediaRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/schedule': {
      id: '/overlay/schedule'
      path: '/overlay/schedule'
      fullPath: '/overlay/schedule'
      preLoaderRoute: typeof OverlayScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/subathon-timer': {
      id: '/overlay/subathon-timer'
      path: '/overlay/subathon-timer'
      fullPath: '/overlay/subathon-timer'
      preLoaderRoute: typeof OverlaySubathonTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/tiktok-tap-goal': {
      id: '/overlay/tiktok-tap-goal'
      path: '/overlay/tiktok-tap-goal'
      fullPath: '/overlay/tiktok-tap-goal'
      preLoaderRoute: typeof OverlayTiktokTapGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/tiktok-tappers': {
      id: '/overlay/tiktok-tappers'
      path: '/overlay/tiktok-tappers'
      fullPath: '/overlay/tiktok-tappers'
      preLoaderRoute: typeof OverlayTiktokTappersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/widgets/': {
      id: '/_authenticated/widgets/'
      path: '/widgets'
      fullPath: '/widgets/'
      preLoaderRoute: typeof AuthenticatedWidgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/widgets/$widgetId': {
      id: '/_authenticated/widgets/$widgetId'
      path: '/widgets/$widgetId'
      fullPath: '/widgets/$widgetId'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/marks/$token/$markId': {
      id: '/marks/$token/$markId'
      path: '/$markId'
      fullPath: '/marks/$token/$markId'
      preLoaderRoute: typeof MarksTokenMarkIdRouteImport
      parentRoute: typeof MarksTokenRoute
    }
    '/_authenticated/subathons/$id/control': {
      id: '/_authenticated/subathons/$id/control'
      path: '/subathons/$id/control'
      fullPath: '/subathons/$id/control'
      preLoaderRoute: typeof AuthenticatedSubathonsIdControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subathons/$id/overlay': {
      id: '/_authenticated/subathons/$id/overlay'
      path: '/subathons/$id/overlay'
      fullPath: '/subathons/$id/overlay'
      preLoaderRoute: typeof AuthenticatedSubathonsIdOverlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subathons/$id/rules': {
      id: '/_authenticated/subathons/$id/rules'
      path: '/subathons/$id/rules'
      fullPath: '/subathons/$id/rules'
      preLoaderRoute: typeof AuthenticatedSubathonsIdRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/widgets/$widgetId/': {
      id: '/_authenticated/widgets/$widgetId/'
      path: '/'
      fullPath: '/widgets/$widgetId/'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdIndexRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/control': {
      id: '/_authenticated/widgets/$widgetId/control'
      path: '/control'
      fullPath: '/widgets/$widgetId/control'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdControlRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/goal': {
      id: '/_authenticated/widgets/$widgetId/goal'
      path: '/goal'
      fullPath: '/widgets/$widgetId/goal'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdGoalRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/rules': {
      id: '/_authenticated/widgets/$widgetId/rules'
      path: '/rules'
      fullPath: '/widgets/$widgetId/rules'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdRulesRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/api/auth/$provider/callback': {
      id: '/api/auth/$provider/callback'
      path: '/api/auth/$provider/callback'
      fullPath: '/api/auth/$provider/callback'
      preLoaderRoute: typeof ApiAuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$provider/start': {
      id: '/api/auth/$provider/start'
      path: '/api/auth/$provider/start'
      fullPath: '/api/auth/$provider/start'
      preLoaderRoute: typeof ApiAuthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/tiktok': {
      id: '/api/auth/callback/tiktok'
      path: '/api/auth/callback/tiktok'
      fullPath: '/api/auth/callback/tiktok'
      preLoaderRoute: typeof ApiAuthCallbackTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session/finish': {
      id: '/api/auth/session/finish'
      path: '/api/auth/session/finish'
      fullPath: '/api/auth/session/finish'
      preLoaderRoute: typeof ApiAuthSessionFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-counter/lookup': {
      id: '/api/live-counter/lookup'
      path: '/api/live-counter/lookup'
      fullPath: '/api/live-counter/lookup'
      preLoaderRoute: typeof ApiLiveCounterLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tuwaiqpay/bills': {
      id: '/api/tuwaiqpay/bills'
      path: '/api/tuwaiqpay/bills'
      fullPath: '/api/tuwaiqpay/bills'
      preLoaderRoute: typeof ApiTuwaiqpayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tuwaiqpay/status': {
      id: '/api/tuwaiqpay/status'
      path: '/api/tuwaiqpay/status'
      fullPath: '/api/tuwaiqpay/status'
      preLoaderRoute: typeof ApiTuwaiqpayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/tuwaiqpay-payment': {
      id: '/api/webhooks/tuwaiqpay-payment'
      path: '/api/webhooks/tuwaiqpay-payment'
      fullPath: '/api/webhooks/tuwaiqpay-payment'
      preLoaderRoute: typeof ApiWebhooksTuwaiqpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clip/$id': {
      id: '/api/public/clip/$id'
      path: '/api/public/clip/$id'
      fullPath: '/api/public/clip/$id'
      preLoaderRoute: typeof ApiPublicClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kick': {
      id: '/api/public/webhooks/kick'
      path: '/api/public/webhooks/kick'
      fullPath: '/api/public/webhooks/kick'
      preLoaderRoute: typeof ApiPublicWebhooksKickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pro-checkout': {
      id: '/api/public/webhooks/pro-checkout'
      path: '/api/public/webhooks/pro-checkout'
      fullPath: '/api/public/webhooks/pro-checkout'
      preLoaderRoute: typeof ApiPublicWebhooksProCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/streamelements': {
      id: '/api/public/webhooks/streamelements'
      path: '/api/public/webhooks/streamelements'
      fullPath: '/api/public/webhooks/streamelements'
      preLoaderRoute: typeof ApiPublicWebhooksStreamelementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/streamlabs': {
      id: '/api/public/webhooks/streamlabs'
      path: '/api/public/webhooks/streamlabs'
      fullPath: '/api/public/webhooks/streamlabs'
      preLoaderRoute: typeof ApiPublicWebhooksStreamlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/twitch': {
      id: '/api/public/webhooks/twitch'
      path: '/api/public/webhooks/twitch'
      fullPath: '/api/public/webhooks/twitch'
      preLoaderRoute: typeof ApiPublicWebhooksTwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/$provider/callback': {
      id: '/api/public/auth/$provider/callback'
      path: '/api/public/auth/$provider/callback'
      fullPath: '/api/public/auth/$provider/callback'
      preLoaderRoute: typeof ApiPublicAuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/$provider/start': {
      id: '/api/public/auth/$provider/start'
      path: '/api/public/auth/$provider/start'
      fullPath: '/api/public/auth/$provider/start'
      preLoaderRoute: typeof ApiPublicAuthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/giveaway/$token/live': {
      id: '/api/public/giveaway/$token/live'
      path: '/api/public/giveaway/$token/live'
      fullPath: '/api/public/giveaway/$token/live'
      preLoaderRoute: typeof ApiPublicGiveawayTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link-in-bio/$slug/live': {
      id: '/api/public/link-in-bio/$slug/live'
      path: '/api/public/link-in-bio/$slug/live'
      fullPath: '/api/public/link-in-bio/$slug/live'
      preLoaderRoute: typeof ApiPublicLinkInBioSlugLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marks/$token/gate': {
      id: '/api/public/marks/$token/gate'
      path: '/api/public/marks/$token/gate'
      fullPath: '/api/public/marks/$token/gate'
      preLoaderRoute: typeof ApiPublicMarksTokenGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marks/$token/live': {
      id: '/api/public/marks/$token/live'
      path: '/api/public/marks/$token/live'
      fullPath: '/api/public/marks/$token/live'
      preLoaderRoute: typeof ApiPublicMarksTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marks/$token/status': {
      id: '/api/public/marks/$token/status'
      path: '/api/public/marks/$token/status'
      fullPath: '/api/public/marks/$token/status'
      preLoaderRoute: typeof ApiPublicMarksTokenStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/advance': {
      id: '/api/public/media-request/$token/advance'
      path: '/api/public/media-request/$token/advance'
      fullPath: '/api/public/media-request/$token/advance'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/live': {
      id: '/api/public/media-request/$token/live'
      path: '/api/public/media-request/$token/live'
      fullPath: '/api/public/media-request/$token/live'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/stream': {
      id: '/api/public/media-request/$token/stream'
      path: '/api/public/media-request/$token/stream'
      fullPath: '/api/public/media-request/$token/stream'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mod-queue/$token/action': {
      id: '/api/public/mod-queue/$token/action'
      path: '/api/public/mod-queue/$token/action'
      fullPath: '/api/public/mod-queue/$token/action'
      preLoaderRoute: typeof ApiPublicModQueueTokenActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mod-queue/$token/queue': {
      id: '/api/public/mod-queue/$token/queue'
      path: '/api/public/mod-queue/$token/queue'
      fullPath: '/api/public/mod-queue/$token/queue'
      preLoaderRoute: typeof ApiPublicModQueueTokenQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/live': {
      id: '/api/public/overlay/$publicId/live'
      path: '/api/public/overlay/$publicId/live'
      fullPath: '/api/public/overlay/$publicId/live'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/meta': {
      id: '/api/public/overlay/$publicId/meta'
      path: '/api/public/overlay/$publicId/meta'
      fullPath: '/api/public/overlay/$publicId/meta'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/stream': {
      id: '/api/public/overlay/$publicId/stream'
      path: '/api/public/overlay/$publicId/stream'
      fullPath: '/api/public/overlay/$publicId/stream'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/schedule/$token/ics': {
      id: '/api/public/schedule/$token/ics'
      path: '/api/public/schedule/$token/ics'
      fullPath: '/api/public/schedule/$token/ics'
      preLoaderRoute: typeof ApiPublicScheduleTokenIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/schedule/$token/live': {
      id: '/api/public/schedule/$token/live'
      path: '/api/public/schedule/$token/live'
      fullPath: '/api/public/schedule/$token/live'
      preLoaderRoute: typeof ApiPublicScheduleTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marks/$token/vod/$markId': {
      id: '/api/public/marks/$token/vod/$markId'
      path: '/api/public/marks/$token/vod/$markId'
      fullPath: '/api/public/marks/$token/vod/$markId'
      preLoaderRoute: typeof ApiPublicMarksTokenVodMarkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWidgetsWidgetIdRouteChildren {
  AuthenticatedWidgetsWidgetIdControlRoute: typeof AuthenticatedWidgetsWidgetIdControlRoute
  AuthenticatedWidgetsWidgetIdGoalRoute: typeof AuthenticatedWidgetsWidgetIdGoalRoute
  AuthenticatedWidgetsWidgetIdRulesRoute: typeof AuthenticatedWidgetsWidgetIdRulesRoute
  AuthenticatedWidgetsWidgetIdIndexRoute: typeof AuthenticatedWidgetsWidgetIdIndexRoute
}

const AuthenticatedWidgetsWidgetIdRouteChildren: AuthenticatedWidgetsWidgetIdRouteChildren =
  {
    AuthenticatedWidgetsWidgetIdControlRoute:
      AuthenticatedWidgetsWidgetIdControlRoute,
    AuthenticatedWidgetsWidgetIdGoalRoute:
      AuthenticatedWidgetsWidgetIdGoalRoute,
    AuthenticatedWidgetsWidgetIdRulesRoute:
      AuthenticatedWidgetsWidgetIdRulesRoute,
    AuthenticatedWidgetsWidgetIdIndexRoute:
      AuthenticatedWidgetsWidgetIdIndexRoute,
  }

const AuthenticatedWidgetsWidgetIdRouteWithChildren =
  AuthenticatedWidgetsWidgetIdRoute._addFileChildren(
    AuthenticatedWidgetsWidgetIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityFeedRoute: typeof AuthenticatedActivityFeedRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedClipCommandRoute: typeof AuthenticatedClipCommandRoute
  AuthenticatedClipsRoute: typeof AuthenticatedClipsRoute
  AuthenticatedCustomCommandsRoute: typeof AuthenticatedCustomCommandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGiveawayRoute: typeof AuthenticatedGiveawayRoute
  AuthenticatedLinkInBioRoute: typeof AuthenticatedLinkInBioRoute
  AuthenticatedLiveCounterRoute: typeof AuthenticatedLiveCounterRoute
  AuthenticatedMarkPointsRoute: typeof AuthenticatedMarkPointsRoute
  AuthenticatedMediaRequestsRoute: typeof AuthenticatedMediaRequestsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedWidgetsWidgetIdRoute: typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  AuthenticatedWidgetsIndexRoute: typeof AuthenticatedWidgetsIndexRoute
  AuthenticatedSubathonsIdControlRoute: typeof AuthenticatedSubathonsIdControlRoute
  AuthenticatedSubathonsIdOverlayRoute: typeof AuthenticatedSubathonsIdOverlayRoute
  AuthenticatedSubathonsIdRulesRoute: typeof AuthenticatedSubathonsIdRulesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityFeedRoute: AuthenticatedActivityFeedRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedClipCommandRoute: AuthenticatedClipCommandRoute,
  AuthenticatedClipsRoute: AuthenticatedClipsRoute,
  AuthenticatedCustomCommandsRoute: AuthenticatedCustomCommandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGiveawayRoute: AuthenticatedGiveawayRoute,
  AuthenticatedLinkInBioRoute: AuthenticatedLinkInBioRoute,
  AuthenticatedLiveCounterRoute: AuthenticatedLiveCounterRoute,
  AuthenticatedMarkPointsRoute: AuthenticatedMarkPointsRoute,
  AuthenticatedMediaRequestsRoute: AuthenticatedMediaRequestsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedWidgetsWidgetIdRoute:
    AuthenticatedWidgetsWidgetIdRouteWithChildren,
  AuthenticatedWidgetsIndexRoute: AuthenticatedWidgetsIndexRoute,
  AuthenticatedSubathonsIdControlRoute: AuthenticatedSubathonsIdControlRoute,
  AuthenticatedSubathonsIdOverlayRoute: AuthenticatedSubathonsIdOverlayRoute,
  AuthenticatedSubathonsIdRulesRoute: AuthenticatedSubathonsIdRulesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarksTokenRouteChildren {
  MarksTokenMarkIdRoute: typeof MarksTokenMarkIdRoute
}

const MarksTokenRouteChildren: MarksTokenRouteChildren = {
  MarksTokenMarkIdRoute: MarksTokenMarkIdRoute,
}

const MarksTokenRouteWithChildren = MarksTokenRoute._addFileChildren(
  MarksTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ModQueueRoute: ModQueueRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BioSlugRoute: BioSlugRoute,
  ClipIdRoute: ClipIdRoute,
  MarksTokenRoute: MarksTokenRouteWithChildren,
  OverlayPublicIdRoute: OverlayPublicIdRoute,
  OverlayGiveawayRoute: OverlayGiveawayRoute,
  OverlayMediaRequestRoute: OverlayMediaRequestRoute,
  OverlayScheduleRoute: OverlayScheduleRoute,
  OverlaySubathonTimerRoute: OverlaySubathonTimerRoute,
  OverlayTiktokTapGoalRoute: OverlayTiktokTapGoalRoute,
  OverlayTiktokTappersRoute: OverlayTiktokTappersRoute,
  USlugRoute: USlugRoute,
  ApiAuthProviderCallbackRoute: ApiAuthProviderCallbackRoute,
  ApiAuthProviderStartRoute: ApiAuthProviderStartRoute,
  ApiAuthCallbackTiktokRoute: ApiAuthCallbackTiktokRoute,
  ApiAuthSessionFinishRoute: ApiAuthSessionFinishRoute,
  ApiLiveCounterLookupRoute: ApiLiveCounterLookupRoute,
  ApiTuwaiqpayBillsRoute: ApiTuwaiqpayBillsRoute,
  ApiTuwaiqpayStatusRoute: ApiTuwaiqpayStatusRoute,
  ApiWebhooksTuwaiqpayPaymentRoute: ApiWebhooksTuwaiqpayPaymentRoute,
  ApiPublicClipIdRoute: ApiPublicClipIdRoute,
  ApiPublicWebhooksKickRoute: ApiPublicWebhooksKickRoute,
  ApiPublicWebhooksProCheckoutRoute: ApiPublicWebhooksProCheckoutRoute,
  ApiPublicWebhooksStreamelementsRoute: ApiPublicWebhooksStreamelementsRoute,
  ApiPublicWebhooksStreamlabsRoute: ApiPublicWebhooksStreamlabsRoute,
  ApiPublicWebhooksTwitchRoute: ApiPublicWebhooksTwitchRoute,
  ApiPublicAuthProviderCallbackRoute: ApiPublicAuthProviderCallbackRoute,
  ApiPublicAuthProviderStartRoute: ApiPublicAuthProviderStartRoute,
  ApiPublicGiveawayTokenLiveRoute: ApiPublicGiveawayTokenLiveRoute,
  ApiPublicLinkInBioSlugLiveRoute: ApiPublicLinkInBioSlugLiveRoute,
  ApiPublicMarksTokenGateRoute: ApiPublicMarksTokenGateRoute,
  ApiPublicMarksTokenLiveRoute: ApiPublicMarksTokenLiveRoute,
  ApiPublicMarksTokenStatusRoute: ApiPublicMarksTokenStatusRoute,
  ApiPublicMediaRequestTokenAdvanceRoute:
    ApiPublicMediaRequestTokenAdvanceRoute,
  ApiPublicMediaRequestTokenLiveRoute: ApiPublicMediaRequestTokenLiveRoute,
  ApiPublicMediaRequestTokenStreamRoute: ApiPublicMediaRequestTokenStreamRoute,
  ApiPublicModQueueTokenActionRoute: ApiPublicModQueueTokenActionRoute,
  ApiPublicModQueueTokenQueueRoute: ApiPublicModQueueTokenQueueRoute,
  ApiPublicOverlayPublicIdLiveRoute: ApiPublicOverlayPublicIdLiveRoute,
  ApiPublicOverlayPublicIdMetaRoute: ApiPublicOverlayPublicIdMetaRoute,
  ApiPublicOverlayPublicIdStreamRoute: ApiPublicOverlayPublicIdStreamRoute,
  ApiPublicScheduleTokenIcsRoute: ApiPublicScheduleTokenIcsRoute,
  ApiPublicScheduleTokenLiveRoute: ApiPublicScheduleTokenLiveRoute,
  ApiPublicMarksTokenVodMarkIdRoute: ApiPublicMarksTokenVodMarkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
